/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-11 05:55:50,435 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-11 05:55:50,436 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-11 05:55:50,436 - INFO - NumExpr defaulting to 8 threads.
2024-05-11 05:55:51,312	INFO scripts.py:1182 -- Did not find any active Ray processes.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eac760>: Failed to establish a new connection: [Errno 111] Connection refused'))

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name_or_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-11 05:56:10 api_server.py:209] vLLM API server version 0.3.3
INFO 05-11 05:56:10 api_server.py:210] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.8, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=8, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=True, scheduler_policy='fcfs', engine_use_ray=False, disable_log_requests=True, max_log_len=None)
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eac6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-11 05:56:14,440	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-11 05:56:16 llm_engine.py:87] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=8, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-11 05:56:16 llm_engine.py:237] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead9c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae290>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaeb60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bba00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eade10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaca60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaca90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadf30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae740>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaed70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bb550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae920>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eacc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eacd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eacaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead690>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadf60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaea40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bba00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae9b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead0c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadf30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae740>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaee00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bb4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaefb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae290>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eafd00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead3f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadcc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae590>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead390>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaeb00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae050>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead600>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bb6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaece0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eac730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bbac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
WARNING 05-11 06:06:10 models.py:48] Using bitblas delta modules
INFO 05-11 06:06:10 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eacbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=45975)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7edf94004dc0>
[36m(RayWorkerVllm pid=45975)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=45975)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=45975)[0m     self.remove()
[36m(RayWorkerVllm pid=45975)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=45975)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=45975)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=46372)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f3be4928dc0>
[36m(RayWorkerVllm pid=46372)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=46372)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=46372)[0m     self.remove()
[36m(RayWorkerVllm pid=46372)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=46372)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=46372)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf010>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=45975)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7edf94004dc0>
[36m(RayWorkerVllm pid=45975)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=45975)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=45975)[0m     self.remove()
[36m(RayWorkerVllm pid=45975)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=45975)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=45975)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadc00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eec640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae080>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaeb60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaceb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eec1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eac9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaef80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaefb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadab0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eec730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eadf60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae230>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaeda0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eec850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bbee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaed10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae5c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eecf40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae680>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaebf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eec400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bbaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eacfa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaff40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eafbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eade70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead120>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eacf40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eafb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd52bb4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eafca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eac070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaead0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eac6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eae680>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaebf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4ead2a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eac7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=45975)[0m Using bitblas
[36m(RayWorkerVllm pid=46135)[0m Using bitblas
[36m(RayWorkerVllm pid=46372)[0m Using bitblas
[36m(RayWorkerVllm pid=45975)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=45975)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=46372)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=46372)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=45975)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=45975)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:14:53 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:14:53 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:14:54 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:14:54 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:15:02 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:03 selector.py:16] Using FlashAttention backend.
INFO 05-11 06:15:17 model_runner.py:155] Loading model weights took 6.1114 GB
INFO 05-11 06:15:17 worker_manager.py:293] Starting prefetching thread
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:18 model_runner.py:155] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:18 worker_manager.py:293] Starting prefetching thread
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:18 model_runner.py:155] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:18 worker_manager.py:293] Starting prefetching thread
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:18 model_runner.py:155] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:18 worker_manager.py:293] Starting prefetching thread
WARNING 05-11 06:15:20 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eaf220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd4eacee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:15:21 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:15:21 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:15:21 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-11 06:15:35 ray_gpu_executor.py:266] # GPU blocks: 13451, # CPU blocks: 1310
INFO 05-11 06:15:38 block_manager.py:264] disable automatic prefix caching
WARNING 05-11 06:15:38 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [38196]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:51078 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 199, 'prompt': 'USER: Help me plan fun family activities for weeknights\nASSISTANT:', 'timestamp': 0, 'model': 'delta-8', 'min_tokens': 274, 'max_tokens': 274}
INFO 05-11 06:15:42 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
WARNING 05-11 06:15:42 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
INFO 05-11 06:15:42 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:15:42 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:42 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:15:42 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:42 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:42 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:42 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:15:42 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:42 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:42 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:42 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:15:42 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:42 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:42 models.py:268] [main] Lossless Compression Disabled
INFO 05-11 06:15:44 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.444 seconds
INFO 05-11 06:15:44 worker_manager.py:353] Main thread loading delta 8 done
INFO 05-11 06:15:44 worker_manager.py:368] [1715379344.3143406] activating delta
INFO 05-11 06:15:44 worker_manager.py:373] [1715379344.4137745] CPU -> GPU time: 0.0994
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:44 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.849 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:44 worker_manager.py:353] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:44 worker_manager.py:368] [1715379344.692047] activating delta
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:44 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.882 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:44 worker_manager.py:353] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:44 worker_manager.py:368] [1715379344.7253127] activating delta
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:44 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.885 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:44 worker_manager.py:353] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:44 worker_manager.py:368] [1715379344.7285373] activating delta
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:15:44 worker_manager.py:373] [1715379344.818866] CPU -> GPU time: 0.1268
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:15:44 worker_manager.py:373] [1715379344.9022229] CPU -> GPU time: 0.1769
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:15:44 worker_manager.py:373] [1715379344.8959982] CPU -> GPU time: 0.1674
INFO 05-11 06:15:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-11 06:15:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-11 06:15:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:01 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:16:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:51080 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.1
sending 1 queries at 0.30000000000000004
sending 1 queries at 0.4
sending 2 queries at 0.5
sending 1 queries at 0.6000000000000001
sending 1 queries at 0.7000000000000001
sending 1 queries at 1.0
sending 1 queries at 1.3
sending 1 queries at 1.4000000000000001
sending 2 queries at 1.6
sending 1 queries at 1.7000000000000002
sending 4 queries at 2.0
sending 1 queries at 2.2
sending 1 queries at 2.4000000000000004
sending 1 queries at 2.6
sending 1 queries at 3.1
sending 1 queries at 3.2
sending 1 queries at 3.3000000000000003
sending 2 queries at 3.5
sending 2 queries at 3.6
sending 1 queries at 3.9000000000000004
sending 1 queries at 4.0
sending 2 queries at 4.1000000000000005
sending 2 queries at 4.3
sending 2 queries at 4.4
sending 1 queries at 4.6000000000000005
sending 1 queries at 4.7
sending 1 queries at 4.800000000000001
sending 1 queries at 5.1000000000000005
sending 1 queries at 5.2
sending 2 queries at 5.300000000000001
sending 2 queries at 5.5
sending 1 queries at 5.6000000000000005
sending 3 queries at 5.7
sending 2 queries at 5.800000000000001
sending 1 queries at 5.9
sending 1 queries at 6.0
sending 3 queries at 6.5
sending 1 queries at 6.6000000000000005
sending 2 queries at 6.7
sending 4 queries at 6.800000000000001
sending 4 queries at 7.0
sending 2 queries at 7.2
sending 2 queries at 7.5
sending 2 queries at 7.9
sending 1 queries at 8.4
sending 1 queries at 8.5
sending 2 queries at 8.6
sending 4 queries at 8.700000000000001
sending 3 queries at 8.8
sending 1 queries at 9.0
sending 2 queries at 9.1
sending 2 queries at 9.200000000000001
sending 1 queries at 9.3
sending 2 queries at 9.600000000000001
sending 1 queries at 9.700000000000001
sending 1 queries at 9.8
sending 2 queries at 9.9
sending 1 queries at 10.0
sending 2 queries at 10.100000000000001
sending 2 queries at 10.3
sending 2 queries at 10.4
sending 1 queries at 10.600000000000001
sending 1 queries at 10.9
sending 1 queries at 11.0
sending 1 queries at 11.100000000000001
sending 1 queries at 11.200000000000001
sending 2 queries at 11.3
sending 1 queries at 11.600000000000001
sending 1 queries at 11.700000000000001
sending 1 queries at 11.9
sending 1 queries at 12.0
sending 1 queries at 12.100000000000001
sending 2 queries at 12.3
sending 1 queries at 12.5
sending 1 queries at 12.600000000000001
sending 1 queries at 12.9
sending 1 queries at 13.0
sending 2 queries at 13.200000000000001
sending 1 queries at 13.600000000000001
sending 1 queries at 13.700000000000001
sending 1 queries at 13.8
sending 3 queries at 13.9
sending 1 queries at 14.0
sending 1 queries at 14.100000000000001
sending 3 queries at 14.200000000000001
sending 1 queries at 14.3
sending 1 queries at 14.4
sending 1 queries at 14.5
sending 1 queries at 14.600000000000001
sending 1 queries at 14.700000000000001
sending 1 queries at 14.8
sending 1 queries at 14.9
sending 1 queries at 15.100000000000001
sending 2 queries at 15.200000000000001
sending 1 queries at 15.5
sending 1 queries at 15.700000000000001
sending 2 queries at 15.8
sending 1 queries at 16.1
sending 1 queries at 16.2
sending 2 queries at 17.0
sending 2 queries at 17.2
sending 2 queries at 17.400000000000002
sending 1 queries at 17.6
sending 1 queries at 17.8
sending 3 queries at 17.900000000000002
sending 1 queries at 18.0
sending 1 queries at 18.1
sending 1 queries at 18.3
sending 1 queries at 18.5
sending 1 queries at 18.900000000000002
sending 2 queries at 19.1
sending 1 queries at 19.200000000000003
sending 2 queries at 19.3
sending 4 queries at 19.400000000000002
sending 2 queries at 19.6
sending 1 queries at 19.700000000000003
sending 1 queries at 20.0
sending 3 queries at 20.1
sending 2 queries at 20.3
sending 1 queries at 20.400000000000002
sending 1 queries at 20.700000000000003
sending 1 queries at 20.8
sending 1 queries at 20.900000000000002
sending 1 queries at 21.0
sending 1 queries at 21.1
sending 3 queries at 21.200000000000003
sending 1 queries at 21.3
sending 1 queries at 21.6
sending 1 queries at 21.700000000000003
sending 2 queries at 21.8
sending 3 queries at 21.900000000000002
sending 1 queries at 22.0
sending 1 queries at 22.1
sending 4 queries at 22.200000000000003
sending 1 queries at 22.3
sending 1 queries at 22.400000000000002
sending 1 queries at 22.5
sending 1 queries at 22.700000000000003
sending 1 queries at 23.200000000000003
sending 1 queries at 23.3
sending 3 queries at 23.400000000000002
sending 2 queries at 23.6
sending 1 queries at 23.700000000000003
sending 1 queries at 23.8
sending 1 queries at 24.0
sending 1 queries at 24.1
sending 1 queries at 24.3
sending 1 queries at 24.400000000000002
sending 1 queries at 24.5
sending 1 queries at 24.6
sending 1 queries at 24.900000000000002
sending 1 queries at 25.0
sending 1 queries at 25.1
sending 1 queries at 25.400000000000002
sending 1 queries at 25.5
sending 2 queries at 25.6
sending 3 queries at 25.700000000000003
sending 2 queries at 25.8
sending 2 queries at 25.900000000000002
sending 1 queries at 26.0
sending 2 queries at 26.200000000000003
sending 2 queries at 26.3
sending 2 queries at 26.5
sending 1 queries at 26.6
sending 3 queries at 26.700000000000003
sending 1 queries at 26.8
sending 1 queries at 27.1
sending 1 queries at 27.3
sending 1 queries at 27.400000000000002
sending 2 queries at 27.700000000000003
sending 1 queries at 27.8
sending 1 queries at 27.900000000000002
sending 1 queries at 28.200000000000003
sending 4 queries at 28.3
sending 1 queries at 28.6
sending 1 queries at 28.700000000000003
sending 1 queries at 28.900000000000002
sending 2 queries at 29.0
sending 2 queries at 29.1
sending 1 queries at 29.6
sending 2 queries at 29.8
INFO 05-11 06:16:52 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
WARNING 05-11 06:16:52 worker_manager.py:335] Missed prefetch, fall back to loading delta 5 now
INFO 05-11 06:16:52 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:16:52 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:52 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:16:52 worker_manager.py:335] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:52 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:52 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:52 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:16:52 worker_manager.py:335] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:52 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:52 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:52 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:16:52 worker_manager.py:335] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:52 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:52 models.py:268] [main] Lossless Compression Disabled
INFO 05-11 06:16:53 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
INFO 05-11 06:16:54 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.423 seconds
INFO 05-11 06:16:54 worker_manager.py:353] Main thread loading delta 5 done
INFO 05-11 06:16:54 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:16:54 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:54 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.896 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:54 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.896 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:54 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.892 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:54 worker_manager.py:353] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:54 worker_manager.py:353] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:54 worker_manager.py:353] Main thread loading delta 5 done
INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 1 to prefetching queue: [5, 1]
INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 7 to prefetching queue: [5, 1, 7]
INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [5, 1, 7, 6]
INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 4 to prefetching queue: [5, 1, 7, 6, 4]
INFO 05-11 06:16:56 worker_manager.py:325] Adding delta 3 to prefetching queue: [5, 1, 7, 6, 4, 3]
WARNING 05-11 06:16:56 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
INFO 05-11 06:16:56 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:16:56 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 1 to prefetching queue: [1]
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 7 to prefetching queue: [1, 7]
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [1, 7, 6]
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 4 to prefetching queue: [1, 7, 6, 4]
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:16:56 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:56 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:56 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 1 to prefetching queue: [1]
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 7 to prefetching queue: [1, 7]
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [1, 7, 6]
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 4 to prefetching queue: [1, 7, 6, 4]
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:16:56 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:56 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:56 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 1 to prefetching queue: [1]
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 7 to prefetching queue: [1, 7]
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [1, 7, 6]
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:55 worker_manager.py:325] Adding delta 4 to prefetching queue: [1, 7, 6, 4]
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:16:56 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:56 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:56 models.py:268] [main] Lossless Compression Disabled
INFO 05-11 06:16:56 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.834 seconds
INFO 05-11 06:16:56 worker_manager.py:278] Prefetching delta 5 done
INFO 05-11 06:16:57 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.615 seconds
INFO 05-11 06:16:57 worker_manager.py:353] Main thread loading delta 1 done
INFO 05-11 06:16:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:16:57 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:57 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.860 seconds
WARNING 05-11 06:16:57 worker_manager.py:335] Missed prefetch, fall back to loading delta 4 now
INFO 05-11 06:16:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:16:57 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:57 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.927 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:57 worker_manager.py:353] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:57 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:57 worker_manager.py:353] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:57 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:57 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.904 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:57 worker_manager.py:353] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:57 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:16:58 worker_manager.py:335] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:58 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:16:58 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:16:58 worker_manager.py:335] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:58 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:16:58 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:16:58 worker_manager.py:335] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:58 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:16:58 models.py:268] [main] Lossless Compression Disabled
INFO 05-11 06:17:00 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.733 seconds
INFO 05-11 06:17:00 worker_manager.py:278] Prefetching delta 7 done
INFO 05-11 06:17:00 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.589 seconds
INFO 05-11 06:17:00 worker_manager.py:353] Main thread loading delta 4 done
INFO 05-11 06:17:00 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:17:00 models.py:268] [prefetching] Lossless Compression Disabled
WARNING 05-11 06:17:00 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
WARNING 05-11 06:17:00 worker_manager.py:344] Discarding prefetching delta 6
INFO 05-11 06:17:00 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:17:00 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:00 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.912 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:00 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.896 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:00 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:00 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.871 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:00 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:00 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:01 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.945 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:01 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.967 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:01 worker_manager.py:353] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:01 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:01 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.935 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:01 worker_manager.py:353] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:01 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:01 worker_manager.py:353] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:01 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:17:01 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:17:01 worker_manager.py:344] Discarding prefetching delta 6
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:01 models.py:268] [main] Lossless Compression Disabled
INFO 05-11 06:17:01 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 0.696 seconds
INFO 05-11 06:17:01 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:17:01 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:17:01 worker_manager.py:344] Discarding prefetching delta 6
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:01 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:17:01 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:17:01 worker_manager.py:344] Discarding prefetching delta 6
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:01 models.py:268] [main] Lossless Compression Disabled
INFO 05-11 06:17:02 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.907 seconds
INFO 05-11 06:17:02 worker_manager.py:353] Main thread loading delta 6 done
INFO 05-11 06:17:02 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:17:02 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:03 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.762 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:03 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:03 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.795 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:03 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:03 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.862 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:04 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:04 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.832 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:04 worker_manager.py:353] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:04 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.857 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:04 worker_manager.py:353] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:04 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.907 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:04 worker_manager.py:353] Main thread loading delta 6 done
INFO 05-11 06:17:04 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.803 seconds
INFO 05-11 06:17:04 worker_manager.py:278] Prefetching delta 3 done
INFO 05-11 06:17:05 metrics.py:276] Avg prompt throughput: 1.6 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:05 worker_manager.py:325] Adding delta 3 to prefetching queue: [3]
[36m(RayWorkerVllm pid=45975)[0m WARNING 05-11 06:17:05 worker_manager.py:335] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:05 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:05 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:05 worker_manager.py:325] Adding delta 3 to prefetching queue: [3]
[36m(RayWorkerVllm pid=46135)[0m WARNING 05-11 06:17:05 worker_manager.py:335] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:05 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:05 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:05 worker_manager.py:325] Adding delta 3 to prefetching queue: [3]
[36m(RayWorkerVllm pid=46372)[0m WARNING 05-11 06:17:05 worker_manager.py:335] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:05 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:05 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:06 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 0.578 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:06 worker_manager.py:353] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:06 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 0.574 seconds
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:06 worker_manager.py:353] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:06 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 0.611 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:06 worker_manager.py:353] Main thread loading delta 3 done
INFO 05-11 06:17:09 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
INFO:     ::1:51266 - "POST /v1/completions HTTP/1.1" 200 OK
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:09 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:09 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:09 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
INFO 05-11 06:17:09 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-11 06:17:09 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:09 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:09 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:10 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:10 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:09 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:09 models.py:268] [prefetching] Lossless Compression Disabled
INFO 05-11 06:17:11 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.358 seconds
INFO 05-11 06:17:11 worker_manager.py:278] Prefetching delta 2 done
INFO 05-11 06:17:11 metrics.py:276] Avg prompt throughput: 156.7 tokens/s, Avg generation throughput: 5.8 tokens/s, Running: 33 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:12 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.859 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:12 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.731 seconds
[36m(RayWorkerVllm pid=46372)[0m INFO 05-11 06:17:12 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:12 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.749 seconds
[36m(RayWorkerVllm pid=45975)[0m INFO 05-11 06:17:12 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=46135)[0m INFO 05-11 06:17:12 worker_manager.py:278] Prefetching delta 2 done
INFO 05-11 06:17:16 metrics.py:276] Avg prompt throughput: 137.5 tokens/s, Avg generation throughput: 4.4 tokens/s, Running: 61 reqs, Swapped: 0 reqs, Pending: 9 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-11 06:17:22 metrics.py:276] Avg prompt throughput: 288.5 tokens/s, Avg generation throughput: 6.7 tokens/s, Running: 92 reqs, Swapped: 0 reqs, Pending: 14 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
total threads: 273
INFO 05-11 06:17:27 metrics.py:276] Avg prompt throughput: 127.3 tokens/s, Avg generation throughput: 5.0 tokens/s, Running: 125 reqs, Swapped: 0 reqs, Pending: 17 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO 05-11 06:17:34 metrics.py:276] Avg prompt throughput: 325.3 tokens/s, Avg generation throughput: 5.6 tokens/s, Running: 155 reqs, Swapped: 0 reqs, Pending: 23 reqs, GPU KV cache usage: 3.4%, CPU KV cache usage: 0.0%
INFO 05-11 06:17:41 metrics.py:276] Avg prompt throughput: 255.4 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 185 reqs, Swapped: 0 reqs, Pending: 29 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 05-11 06:17:48 metrics.py:276] Avg prompt throughput: 272.8 tokens/s, Avg generation throughput: 4.7 tokens/s, Running: 215 reqs, Swapped: 0 reqs, Pending: 35 reqs, GPU KV cache usage: 5.4%, CPU KV cache usage: 0.0%
INFO:     ::1:51576 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51298 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:17:54 metrics.py:276] Avg prompt throughput: 123.1 tokens/s, Avg generation throughput: 78.2 tokens/s, Running: 232 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%
INFO:     ::1:51782 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51672 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51258 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51290 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51304 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51310 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51864 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51307 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51434 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51608 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 145.5 tokens/s, Running: 220 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 6.1%, CPU KV cache usage: 0.0%
INFO:     ::1:51302 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51596 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51720 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51842 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51416 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51832 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51590 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51412 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51638 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51320 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51790 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51796 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51554 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51722 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51664 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 139.1 tokens/s, Running: 205 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%
INFO:     ::1:51308 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51470 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51644 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51250 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51500 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51836 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51586 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 134.6 tokens/s, Running: 201 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 6.4%, CPU KV cache usage: 0.0%
INFO:     ::1:51846 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51811 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51838 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 132.8 tokens/s, Running: 198 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 6.8%, CPU KV cache usage: 0.0%
INFO:     ::1:51680 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51572 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:24 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 131.3 tokens/s, Running: 194 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 7.0%, CPU KV cache usage: 0.0%
INFO:     ::1:51444 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51504 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51336 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51544 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:30 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 128.9 tokens/s, Running: 192 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 7.2%, CPU KV cache usage: 0.0%
INFO 05-11 06:18:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 124.5 tokens/s, Running: 191 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 7.6%, CPU KV cache usage: 0.0%
INFO:     ::1:51604 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51284 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51774 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 127.6 tokens/s, Running: 187 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 7.9%, CPU KV cache usage: 0.0%
INFO:     ::1:51432 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51264 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51736 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51506 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51584 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51792 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 125.3 tokens/s, Running: 182 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 8.0%, CPU KV cache usage: 0.0%
INFO:     ::1:51652 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51344 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51858 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:18:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 123.6 tokens/s, Running: 179 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 8.2%, CPU KV cache usage: 0.0%
INFO:     ::1:51420 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51248 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51278 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 122.0 tokens/s, Running: 176 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 8.5%, CPU KV cache usage: 0.0%
INFO:     ::1:51374 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51362 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51436 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 120.3 tokens/s, Running: 173 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 8.8%, CPU KV cache usage: 0.0%
INFO:     ::1:51758 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51566 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 119.3 tokens/s, Running: 172 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 8.9%, CPU KV cache usage: 0.0%
INFO:     ::1:51738 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 118.9 tokens/s, Running: 171 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.2%, CPU KV cache usage: 0.0%
INFO:     ::1:51748 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51772 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51239 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 118.0 tokens/s, Running: 167 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.4%, CPU KV cache usage: 0.0%
INFO:     ::1:51712 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51508 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51368 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51324 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51464 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 93.7 tokens/s, Running: 163 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.6%, CPU KV cache usage: 0.0%
INFO:     ::1:51752 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51478 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51240 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51802 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51734 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:35 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 127.6 tokens/s, Running: 158 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.4%, CPU KV cache usage: 0.0%
INFO:     ::1:51540 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51710 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 111.7 tokens/s, Running: 156 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.6%, CPU KV cache usage: 0.0%
INFO:     ::1:51546 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:46 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 110.6 tokens/s, Running: 154 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.9%, CPU KV cache usage: 0.0%
INFO:     ::1:51424 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51448 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51418 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 109.4 tokens/s, Running: 152 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 10.1%, CPU KV cache usage: 0.0%
INFO:     ::1:51260 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:19:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 108.5 tokens/s, Running: 149 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 10.0%, CPU KV cache usage: 0.0%
INFO:     ::1:51854 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51700 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51764 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51454 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51570 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:20:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 106.2 tokens/s, Running: 143 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.9%, CPU KV cache usage: 0.0%
INFO:     ::1:51522 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51868 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51754 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51514 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51480 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:20:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 104.1 tokens/s, Running: 140 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 10.1%, CPU KV cache usage: 0.0%
INFO:     ::1:51526 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51276 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51740 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51600 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:20:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 102.0 tokens/s, Running: 137 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 10.1%, CPU KV cache usage: 0.0%
INFO:     ::1:51516 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51348 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51273 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51476 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:20:19 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 99.3 tokens/s, Running: 130 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.7%, CPU KV cache usage: 0.0%
INFO:     ::1:51632 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51242 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51622 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51812 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51602 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51263 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51770 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-11 06:20:25 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 93.9 tokens/s, Running: 126 reqs, Swapped: 0 reqs, Pending: 37 reqs, GPU KV cache usage: 9.7%, CPU KV cache usage: 0.0%
INFO:     ::1:51786 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51690 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51662 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:51488 - "POST /v1/completions HTTP/1.1" 200 OK
slurmstepd: error: *** JOB 3669934 ON HOST-10-140-60-7 CANCELLED AT 2024-05-11T06:20:26 ***
