/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-17 19:41:56,465 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-17 19:41:56,465 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-17 19:41:56,465 - INFO - NumExpr defaulting to 8 threads.
2024-05-17 19:41:57,843	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5450>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 19:42:13 api_server.py:191] vLLM API server version 0.3.3
INFO 05-17 19:42:13 api_server.py:192] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8'), Delta(name='delta-9', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9'), Delta(name='delta-10', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10'), Delta(name='delta-11', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11'), Delta(name='delta-12', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12'), Delta(name='delta-13', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13'), Delta(name='delta-14', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14'), Delta(name='delta-15', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15'), Delta(name='delta-16', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16'), Delta(name='delta-17', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17'), Delta(name='delta-18', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18'), Delta(name='delta-19', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19'), Delta(name='delta-20', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20'), Delta(name='delta-21', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21'), Delta(name='delta-22', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22'), Delta(name='delta-23', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23'), Delta(name='delta-24', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24'), Delta(name='delta-25', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25'), Delta(name='delta-26', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26'), Delta(name='delta-27', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27'), Delta(name='delta-28', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28'), Delta(name='delta-29', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29'), Delta(name='delta-30', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30'), Delta(name='delta-31', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31'), Delta(name='delta-32', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.85, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=24, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=True, scheduler_policy='fcfs', max_swap_slots=1, max_cpu_models=4, enable_swap=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-17 19:42:17,270	INFO worker.py:1749 -- Started a local Ray instance.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-17 19:42:19 llm_engine.py:90] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=24, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), swap_config=None, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-17 19:42:19 llm_engine.py:243] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5420>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a41f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a65f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6560>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a55d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6080>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a59c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a50f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6920>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a69b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6980>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a50c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5330>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a66b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a70a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a61d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a48e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a52d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a42b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a58d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5450>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5741480a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a63b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a79d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc57467fd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5960>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a72b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a67a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a74c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
WARNING 05-17 19:51:59 models.py:48] Using bitblas delta modules
INFO 05-17 19:51:59 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=16160)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f248cffa200>
[36m(RayWorkerVllm pid=16160)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=16160)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=16160)[0m     self.remove()
[36m(RayWorkerVllm pid=16160)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=16160)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=16160)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=16466)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f45a015e200>
[36m(RayWorkerVllm pid=16466)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=16466)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=16466)[0m     self.remove()
[36m(RayWorkerVllm pid=16466)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=16466)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=16466)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7340>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=16160)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f248cffa200>
[36m(RayWorkerVllm pid=16160)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=16160)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=16160)[0m     self.remove()
[36m(RayWorkerVllm pid=16160)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=16160)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=16160)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc574148520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6890>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a46d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=16160)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f248cffa200>
[36m(RayWorkerVllm pid=16160)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=16160)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=16160)[0m     self.remove()
[36m(RayWorkerVllm pid=16160)[0m   File "/home/xiayao/.local/lib/python3.10/site-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=16160)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=16160)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5741489a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a70a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc574148340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5660>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a45b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc574148460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a66e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc574148be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6890>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a58d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5741492a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc574148820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a4df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a46a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a68f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a74f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5690>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6020>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6050>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a76d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc574149720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a6320>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a68f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a74f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5690>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc57467fd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5780>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a53c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a5990>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=16160)[0m Using bitblas
[36m(RayWorkerVllm pid=16315)[0m Using bitblas
[36m(RayWorkerVllm pid=16466)[0m Using bitblas
[36m(RayWorkerVllm pid=16160)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=16160)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=16466)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=16466)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=16160)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=16160)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=16160)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=16160)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/9010a150477030a56eb8633d947f9b0c90c0f0da5abb493d7382582dac6503ab/tvm_rt_mod'
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:00:41 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:00:41 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:00:47 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:00:47 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:01:56 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:01:56 selector.py:16] Using FlashAttention backend.
INFO 05-17 20:02:07 model_runner.py:161] Loading model weights took 6.1114 GB
INFO 05-17 20:02:07 worker_manager.py:297] Starting prefetching thread
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7880>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:08 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:09 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:09 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:09 worker_manager.py:297] Starting prefetching thread
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:09 model_runner.py:161] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:09 worker_manager.py:297] Starting prefetching thread
WARNING 05-17 20:02:11 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5746a7e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:02:12 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:02:12 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:02:12 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-17 20:02:25 ray_gpu_executor.py:275] # GPU blocks: 6431, # CPU blocks: 1310
INFO 05-17 20:02:27 scheduler.py:136] Using fcfs policy.
INFO 05-17 20:02:27 block_manager.py:264] disable automatic prefix caching
WARNING 05-17 20:02:28 serving_chat.py:373] No chat template provided. Chat API will not work.
INFO:     Started server process [8404]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:40352 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 0, 'prompt': 'USER: What is the difference between OpenCL and CUDA?\nASSISTANT:', 'timestamp': 0, 'model': 'delta-4', 'min_tokens': 171, 'max_tokens': 171}
INFO 05-17 20:02:29 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
WARNING 05-17 20:02:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
INFO 05-17 20:02:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:02:29 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:29 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:02:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:29 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:29 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:02:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:29 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:29 worker_manager.py:332] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:02:29 worker_manager.py:344] Missed prefetch, fall back to loading delta 4 now
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:29 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:29 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:02:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.481 seconds
INFO 05-17 20:02:31 worker_manager.py:364] Main thread loading delta 4 done
INFO 05-17 20:02:31 worker_manager.py:379] [1715947351.2468476] activating delta
INFO 05-17 20:02:31 worker_manager.py:384] [1715947351.3460715] CPU -> GPU time: 0.0992
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.931 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.929 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.931 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:31 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:31 worker_manager.py:379] [1715947351.6678376] activating delta
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:31 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:31 worker_manager.py:379] [1715947351.666122] activating delta
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:31 worker_manager.py:364] Main thread loading delta 4 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:31 worker_manager.py:379] [1715947351.667508] activating delta
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:02:31 worker_manager.py:384] [1715947351.8297222] CPU -> GPU time: 0.1618
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:02:31 worker_manager.py:384] [1715947351.8347542] CPU -> GPU time: 0.1686
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:02:31 worker_manager.py:384] [1715947351.843473] CPU -> GPU time: 0.1759
INFO 05-17 20:02:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 20:02:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-17 20:02:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:02:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:02:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:02:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:03:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 20:03:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-17 20:03:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:40354 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 0.8
sending 1 queries at 2.1
sending 1 queries at 3.0
sending 1 queries at 3.8000000000000003
sending 1 queries at 4.4
sending 1 queries at 5.4
sending 1 queries at 6.0
sending 1 queries at 8.200000000000001
sending 1 queries at 11.5
sending 1 queries at 12.0
sending 1 queries at 13.600000000000001
sending 1 queries at 14.3
sending 1 queries at 15.200000000000001
sending 2 queries at 17.8
sending 2 queries at 17.900000000000002
sending 1 queries at 19.700000000000003
sending 1 queries at 21.200000000000003
sending 1 queries at 23.3
sending 1 queries at 27.1
sending 1 queries at 28.700000000000003
sending 1 queries at 29.3
INFO 05-17 20:03:17 worker_manager.py:332] Adding delta 20 to prefetching queue: [20]
WARNING 05-17 20:03:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
INFO 05-17 20:03:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:17 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:17 worker_manager.py:332] Adding delta 20 to prefetching queue: [20]
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:17 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:17 worker_manager.py:332] Adding delta 20 to prefetching queue: [20]
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:17 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:17 worker_manager.py:332] Adding delta 20 to prefetching queue: [20]
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:17 worker_manager.py:344] Missed prefetch, fall back to loading delta 20 now
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:17 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:17 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:03:18 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:29 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 12.269 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:29 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:31 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.760 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:31 worker_manager.py:364] Main thread loading delta 20 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:33 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 15.758 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:33 worker_manager.py:364] Main thread loading delta 20 done
INFO 05-17 20:03:34 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 16.609 seconds
INFO 05-17 20:03:34 worker_manager.py:364] Main thread loading delta 20 done
INFO 05-17 20:03:34 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:34 models.py:263] [prefetching] Lossless Compression Disabled
INFO 05-17 20:03:35 metrics.py:276] Avg prompt throughput: 1.9 tokens/s, Avg generation throughput: 0.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 1 to prefetching queue: [6, 1]
INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 2 to prefetching queue: [6, 1, 2]
INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 5 to prefetching queue: [6, 1, 2, 5]
INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 3 to prefetching queue: [6, 1, 2, 5, 3]
INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 29 to prefetching queue: [6, 1, 2, 5, 3, 29]
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 1 to prefetching queue: [6, 1]
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 2 to prefetching queue: [6, 1, 2]
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 5 to prefetching queue: [6, 1, 2, 5]
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 3 to prefetching queue: [6, 1, 2, 5, 3]
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 29 to prefetching queue: [6, 1, 2, 5, 3, 29]
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 1 to prefetching queue: [6, 1]
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 2 to prefetching queue: [6, 1, 2]
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 5 to prefetching queue: [6, 1, 2, 5]
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 3 to prefetching queue: [6, 1, 2, 5, 3]
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 29 to prefetching queue: [6, 1, 2, 5, 3, 29]
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 1 to prefetching queue: [6, 1]
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 2 to prefetching queue: [6, 1, 2]
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 5 to prefetching queue: [6, 1, 2, 5]
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 3 to prefetching queue: [6, 1, 2, 5, 3]
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 worker_manager.py:332] Adding delta 29 to prefetching queue: [6, 1, 2, 5, 3, 29]
WARNING 05-17 20:03:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
INFO 05-17 20:03:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:35 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:03:35 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.415 seconds
INFO 05-17 20:03:35 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:35 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:35 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:35 worker_manager.py:344] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:35 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:03:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.489 seconds
INFO 05-17 20:03:37 worker_manager.py:364] Main thread loading delta 1 done
INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:37 models.py:263] [prefetching] Lossless Compression Disabled
WARNING 05-17 20:03:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
WARNING 05-17 20:03:37 worker_manager.py:353] Discarding prefetching delta 2
INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.915 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:37 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:37 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.868 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:37 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:37 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:37 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.976 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:37 worker_manager.py:364] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:37 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:37 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:37 worker_manager.py:344] Missed prefetch, fall back to loading delta 2 now
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:37 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:37 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:03:39 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.694 seconds
INFO 05-17 20:03:39 worker_manager.py:278] Prefetching delta 2 done
INFO 05-17 20:03:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.783 seconds
INFO 05-17 20:03:40 worker_manager.py:364] Main thread loading delta 2 done
INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:40 models.py:263] [prefetching] Lossless Compression Disabled
WARNING 05-17 20:03:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.833 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.874 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.853 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 worker_manager.py:278] Prefetching delta 6 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.950 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.963 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.947 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 worker_manager.py:364] Main thread loading delta 2 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:40 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:40 worker_manager.py:344] Missed prefetch, fall back to loading delta 3 now
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:40 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:03:41 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.065 seconds
INFO 05-17 20:03:41 worker_manager.py:278] Prefetching delta 5 done
INFO 05-17 20:03:42 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 1.567 seconds
INFO 05-17 20:03:42 worker_manager.py:364] Main thread loading delta 3 done
INFO 05-17 20:03:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:42 models.py:263] [prefetching] Lossless Compression Disabled
WARNING 05-17 20:03:42 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
INFO 05-17 20:03:42 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:42 models.py:263] [main] Lossless Compression Disabled
total threads: 23
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.813 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.835 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.922 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.920 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:43 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.912 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:43 worker_manager.py:353] Discarding prefetching delta 5
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:43 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:43 worker_manager.py:353] Discarding prefetching delta 5
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:43 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:43 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 3.022 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:44 worker_manager.py:364] Main thread loading delta 3 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:44 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:44 worker_manager.py:344] Missed prefetch, fall back to loading delta 5 now
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:44 worker_manager.py:353] Discarding prefetching delta 5
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:44 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:44 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:03:45 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.954 seconds
INFO 05-17 20:03:45 worker_manager.py:278] Prefetching delta 3 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.960 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.970 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:46 worker_manager.py:278] Prefetching delta 5 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:46 worker_manager.py:278] Prefetching delta 5 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.921 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:46 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.938 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:46 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:46 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:46 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:46 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:46 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.967 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:47 worker_manager.py:278] Prefetching delta 5 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:47 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 2.930 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:47 worker_manager.py:364] Main thread loading delta 5 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:47 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:47 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=16160)[0m WARNING 05-17 20:03:48 worker_manager.py:353] Discarding prefetching delta 29
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=16315)[0m WARNING 05-17 20:03:48 worker_manager.py:353] Discarding prefetching delta 29
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:48 models.py:263] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:48 worker_manager.py:344] Missed prefetch, fall back to loading delta 29 now
[36m(RayWorkerVllm pid=16466)[0m WARNING 05-17 20:03:48 worker_manager.py:353] Discarding prefetching delta 29
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:48 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:03:48 models.py:263] [main] Lossless Compression Disabled
INFO 05-17 20:03:54 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.361 seconds
INFO 05-17 20:03:54 worker_manager.py:364] Main thread loading delta 29 done
INFO 05-17 20:03:54 models.py:210] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-17 20:03:54 models.py:263] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.177 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.647 seconds
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:57 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=16315)[0m INFO 05-17 20:03:57 worker_manager.py:278] Prefetching delta 29 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 9.534 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:57 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 10.982 seconds
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:57 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=16160)[0m INFO 05-17 20:03:58 worker_manager.py:278] Prefetching delta 29 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:04:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 11.619 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:04:00 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 13.396 seconds
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:04:00 worker_manager.py:364] Main thread loading delta 29 done
[36m(RayWorkerVllm pid=16466)[0m INFO 05-17 20:04:00 worker_manager.py:278] Prefetching delta 29 done
INFO 05-17 20:04:01 models.py:321] Disk -> CPU: Loaded 1674.62 MiB in 7.585 seconds
INFO 05-17 20:04:02 worker_manager.py:278] Prefetching delta 29 done
INFO 05-17 20:04:03 metrics.py:276] Avg prompt throughput: 0.7 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%
INFO:     ::1:40548 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:04:08 metrics.py:276] Avg prompt throughput: 104.2 tokens/s, Avg generation throughput: 20.4 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%
INFO:     ::1:40528 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:04:14 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.6 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:40518 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:04:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.1 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 20:04:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.8 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:04:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.7 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:04:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.7 tokens/s, Running: 20 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:40594 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:04:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.2 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:40546 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:04:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.8 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:40516 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:04:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.8 tokens/s, Running: 17 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:40588 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.1 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 20:05:06 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.4 tokens/s, Running: 16 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO:     ::1:40498 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:11 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.0 tokens/s, Running: 15 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO:     ::1:40500 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 16.8 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
INFO 05-17 20:05:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-17 20:05:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 14 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:40530 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 13 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO:     ::1:40572 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 12 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.6%, CPU KV cache usage: 0.0%
INFO:     ::1:40564 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:40502 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.6 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:40544 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.6 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:40524 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:05:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.7 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.2 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.3 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:40486 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:06:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.0 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:16 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.8 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.7 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     ::1:40478 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:06:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.9 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 11.5 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:40592 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:06:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.5 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.5 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.6 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO:     ::1:40492 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:06:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.1 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 20:06:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.3 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.3 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO:     ::1:40508 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:07:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.9 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.8 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO:     ::1:40556 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:07:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.3 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
INFO:     ::1:40496 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-17 20:07:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:48 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 20:07:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 20:08:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 20:08:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 05-17 20:08:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO:     ::1:40550 - "POST /v1/completions HTTP/1.1" 200 OK
Results written to .artifact/benchmarks/results/a86468e2-7d88-45eb-be90-bd08355a4d3c.jsonl
Killing process 8404...
/var/spool/slurmd/job3677170/slurm_script: line 45:  8371 Killed                  apptainer run --nv --home /mnt/petrelfs/huqinghao/xzyao/:/home/xiayao --bind /mnt/petrelfs/huqinghao/xzyao/code/vllm:/vllm --bind /mnt/petrelfs/huqinghao/xzyao/code/triteia:/triteia --env PYTHONPATH=/vllm:/triteia --env CUDA_LAUNCH_BLOCKING=1 --env TVM_TARGET=nvidia/nvidia-a100 --env TRANSFORMERS_OFFLINE=1 --env NUMEXPR_MAX_THREADS=128 --env USE_BITBLAS=1 --env BITBLAS_TARGET=nvidia/nvidia-a100 --env RAY_DEDUP_LOGS=0 --workdir /vllm /mnt/petrelfs/huqinghao/xzyao/images/vllm-0.4.1.sif python3 /vllm/vllm/entrypoints/openai/api_server.py --model /vllm/.idea/full_models/Llama-2-13b-hf --enable-delta --disable-log-requests --gpu-memory-utilization 0.85 --delta-modules delta-1=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1 delta-2=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2 delta-3=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3 delta-4=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4 delta-5=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5 delta-6=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6 delta-7=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7 delta-8=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8 delta-9=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-9 delta-10=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-10 delta-11=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-11 delta-12=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-12 delta-13=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-13 delta-14=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-14 delta-15=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-15 delta-16=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-16 delta-17=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-17 delta-18=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-18 delta-19=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-19 delta-20=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-20 delta-21=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-21 delta-22=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-22 delta-23=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-23 delta-24=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-24 delta-25=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-25 delta-26=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-26 delta-27=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-27 delta-28=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-28 delta-29=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-29 delta-30=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-30 delta-31=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-31 delta-32=/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-32 --max-deltas 24 --max-cpu-deltas 32 --tensor-parallel-size 4 --enforce-eager --enable-prefetch
