/mnt/hwfile/huqinghao/miniconda3/bin/python
2024-05-09 03:16:23,458 - INFO - Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-05-09 03:16:23,458 - INFO - Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-05-09 03:16:23,458 - INFO - NumExpr defaulting to 8 threads.
2024-05-09 03:16:24,996	INFO scripts.py:1182 -- Did not find any active Ray processes.

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f845b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name_or_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85330>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO 05-09 03:16:39 api_server.py:202] vLLM API server version 0.3.3
INFO 05-09 03:16:39 api_server.py:203] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[], delta_modules=[Delta(name='delta-1', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-1'), Delta(name='delta-2', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-2'), Delta(name='delta-3', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-3'), Delta(name='delta-4', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-4'), Delta(name='delta-5', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-5'), Delta(name='delta-6', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-6'), Delta(name='delta-7', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-7'), Delta(name='delta-8', local_path='/vllm/.idea/models/13b/lmsys.vicuna-13b-v1.5.4b75s128g-8')], swap_modules=[], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=2048, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, seed=0, swap_space=4, gpu_memory_utilization=0.8, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=32, enable_delta=True, max_deltas=2, max_cpu_deltas=32, max_delta_bitwidth=4, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_prefetch=True, scheduler_policy='deltaserve', engine_use_ray=False, disable_log_requests=True, max_log_len=None)
2024-05-09 03:16:42,580	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-09 03:16:45 llm_engine.py:87] Initializing an LLM engine (v0.3.3) with config: model='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer='/vllm/.idea/full_models/Llama-2-13b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, lora_config=None, delta_config=DeltaConfig(max_deltas=2, max_bitwidth=4, delta_dtype=torch.int8, max_cpu_deltas=32, delta_extra_vocab_size=0, pack_factor=Fraction(2, 1), kernel=<QuantKernel.TRITON: 'triton'>), max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 05-09 03:16:45 llm_engine.py:237] ignored verifying delta_config
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f853f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f840d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f864d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86410>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85990>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f850c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86800>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f868c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f855a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f847c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f840a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86290>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f869e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f874f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f866b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f879a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86500>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84190>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85360>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f871f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f63df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86830>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f860e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using bitblas
WARNING 05-09 03:26:25 models.py:48] Using bitblas delta modules
INFO 05-09 03:26:25 selector.py:16] Using FlashAttention backend.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87820>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=86687)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f8a649f4dc0>
[36m(RayWorkerVllm pid=86687)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=86687)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=86687)[0m     self.remove()
[36m(RayWorkerVllm pid=86687)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=86687)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=86687)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
[36m(RayWorkerVllm pid=86917)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f348c9e8dc0>
[36m(RayWorkerVllm pid=86917)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=86917)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=86917)[0m     self.remove()
[36m(RayWorkerVllm pid=86917)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=86917)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=86917)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=86917)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f348c9e8dc0>
[36m(RayWorkerVllm pid=86917)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=86917)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=86917)[0m     self.remove()
[36m(RayWorkerVllm pid=86917)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=86917)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=86917)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f861d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4c880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4c370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f859c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f875b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86470>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85000>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4c970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86830>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4cac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87010>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86020>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86200>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4d180>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=86687)[0m Exception ignored in: <function TempDirectory.__del__ at 0x7f8a649f4dc0>
[36m(RayWorkerVllm pid=86687)[0m Traceback (most recent call last):
[36m(RayWorkerVllm pid=86687)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 145, in __del__
[36m(RayWorkerVllm pid=86687)[0m     self.remove()
[36m(RayWorkerVllm pid=86687)[0m   File "/usr/local/lib/python3.10/dist-packages/bitblas/3rdparty/tvm/python/tvm/contrib/utils.py", line 121, in remove
[36m(RayWorkerVllm pid=86687)[0m     if self.temp_dir:
[36m(RayWorkerVllm pid=86687)[0m AttributeError: 'TempDirectory' object has no attribute 'temp_dir'
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f864a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f864d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4c700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86080>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85120>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86350>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85840>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85870>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f867d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85540>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f63a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85810>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f853f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85c60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f867a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4d270>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85f00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86350>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4d630>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f853c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4c970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85f00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85720>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86350>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4cc40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f85c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f84220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f853c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=86525)[0m Using bitblas
[36m(RayWorkerVllm pid=86687)[0m Using bitblas
[36m(RayWorkerVllm pid=86917)[0m Using bitblas
[36m(RayWorkerVllm pid=86687)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=86687)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=86917)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=86917)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=86917)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=86917)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/c96df0f34eb23be516ef0126651d4e78b151337f28ebc87cc5492d79d135855f/tvm_rt_mod'
[36m(RayWorkerVllm pid=86687)[0m BitBLAS Operator not loaded, retrying in 5 seconds...
[36m(RayWorkerVllm pid=86687)[0m Error: [Errno 17] File exists: '/home/xiayao/.cache/bitblas/nvidia/nvidia-a100/74a32f5266e089934c0fa07291cec35e032197f9ad2a95c4326036f89b5bd8e6/tvm_rt_mod'
[36m(RayWorkerVllm pid=86525)[0m WARNING 05-09 03:35:10 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:35:10 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=86917)[0m WARNING 05-09 03:35:18 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:35:18 selector.py:16] Using FlashAttention backend.
[36m(RayWorkerVllm pid=86687)[0m WARNING 05-09 03:40:02 models.py:48] Using bitblas delta modules
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:03 selector.py:16] Using FlashAttention backend.
INFO 05-09 03:40:16 model_runner.py:155] Loading model weights took 6.1114 GB
INFO 05-09 03:40:16 worker_manager.py:293] Starting prefetching thread
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f87520>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:17 model_runner.py:155] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:17 worker_manager.py:293] Starting prefetching thread
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:17 model_runner.py:155] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:17 worker_manager.py:293] Starting prefetching thread
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:17 model_runner.py:155] Loading model weights took 6.1114 GB
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:17 worker_manager.py:293] Starting prefetching thread
WARNING 05-09 03:40:19 quant_linear_triton.py:557] We should warm up the kernel here 
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616f86d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
[36m(RayWorkerVllm pid=86917)[0m WARNING 05-09 03:40:20 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=86525)[0m WARNING 05-09 03:40:20 quant_linear_triton.py:557] We should warm up the kernel here 
[36m(RayWorkerVllm pid=86687)[0m WARNING 05-09 03:40:20 quant_linear_triton.py:557] We should warm up the kernel here 
INFO 05-09 03:40:33 ray_gpu_executor.py:266] # GPU blocks: 16701, # CPU blocks: 1310
INFO 05-09 03:40:36 block_manager.py:264] disable automatic prefix caching
WARNING 05-09 03:40:36 serving_chat.py:373] No chat template provided. Chat API will not work.
Waiting for 10 secs for the system to be ready: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sysinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa616b4da80>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO:     Started server process [78870]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     ::1:46188 - "GET /sysinfo HTTP/1.1" 200 OK
Translating from base-model to /vllm/.idea/full_models/Llama-2-13b-hf
Warming up starts
{'id': 7, 'prompt': 'USER: How to parallelize a neural network?\nASSISTANT:', 'timestamp': 0, 'model': 'delta-1', 'min_tokens': 258, 'max_tokens': 258}
INFO 05-09 03:40:46 worker_manager.py:325] Adding delta 1 to prefetching queue: [1]
WARNING 05-09 03:40:46 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
INFO 05-09 03:40:46 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:40:46 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:46 worker_manager.py:325] Adding delta 1 to prefetching queue: [1]
[36m(RayWorkerVllm pid=86525)[0m WARNING 05-09 03:40:46 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:46 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:46 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:46 worker_manager.py:325] Adding delta 1 to prefetching queue: [1]
[36m(RayWorkerVllm pid=86687)[0m WARNING 05-09 03:40:46 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:46 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:46 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:46 worker_manager.py:325] Adding delta 1 to prefetching queue: [1]
[36m(RayWorkerVllm pid=86917)[0m WARNING 05-09 03:40:46 worker_manager.py:335] Missed prefetch, fall back to loading delta 1 now
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:46 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:46 models.py:268] [main] Lossless Compression Disabled
INFO 05-09 03:40:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:40:48 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.581 seconds
INFO 05-09 03:40:48 worker_manager.py:353] Main thread loading delta 1 done
INFO 05-09 03:40:48 worker_manager.py:368] [1715197248.6052864] activating delta
INFO 05-09 03:40:48 worker_manager.py:373] [1715197248.7037544] CPU -> GPU time: 0.0984
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:48 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.008 seconds
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:49 worker_manager.py:353] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:49 worker_manager.py:368] [1715197249.0225153] activating delta
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:48 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.025 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:48 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.041 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:49 worker_manager.py:353] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:49 worker_manager.py:368] [1715197249.0278738] activating delta
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:49 worker_manager.py:353] Main thread loading delta 1 done
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:49 worker_manager.py:368] [1715197249.05436] activating delta
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:40:49 worker_manager.py:373] [1715197249.1552014] CPU -> GPU time: 0.1326
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:40:49 worker_manager.py:373] [1715197249.187308] CPU -> GPU time: 0.1594
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:40:49 worker_manager.py:373] [1715197249.217882] CPU -> GPU time: 0.1635
INFO 05-09 03:40:52 metrics.py:276] Avg prompt throughput: 3.3 tokens/s, Avg generation throughput: 1.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:40:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:28 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:33 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:38 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:43 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:41:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:46190 - "POST /v1/completions HTTP/1.1" 200 OK
Warming up ends
Issuing queries
sending 1 queries at 1.6
sending 1 queries at 4.2
sending 1 queries at 6.0
sending 1 queries at 7.6000000000000005
sending 1 queries at 8.700000000000001
sending 1 queries at 10.8
sending 1 queries at 11.9
sending 1 queries at 16.400000000000002
sending 1 queries at 23.0
sending 1 queries at 23.900000000000002
sending 1 queries at 27.1
sending 1 queries at 28.6
sending 1 queries at 30.3
sending 1 queries at 35.5
sending 1 queries at 35.6
sending 2 queries at 35.800000000000004
sending 1 queries at 39.400000000000006
sending 1 queries at 42.400000000000006
sending 1 queries at 46.5
sending 1 queries at 54.2
sending 1 queries at 57.400000000000006
sending 1 queries at 58.6
INFO 05-09 03:41:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [6]
WARNING 05-09 03:41:55 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
INFO 05-09 03:41:55 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:41:55 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=86525)[0m WARNING 05-09 03:41:55 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:55 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:55 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=86687)[0m WARNING 05-09 03:41:55 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:55 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:55 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:55 worker_manager.py:325] Adding delta 6 to prefetching queue: [6]
[36m(RayWorkerVllm pid=86917)[0m WARNING 05-09 03:41:55 worker_manager.py:335] Missed prefetch, fall back to loading delta 6 now
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:55 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:55 models.py:268] [main] Lossless Compression Disabled
INFO 05-09 03:41:56 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.561 seconds
INFO 05-09 03:41:57 worker_manager.py:353] Main thread loading delta 6 done
INFO 05-09 03:41:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 2.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:57 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.062 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:57 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.031 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:57 worker_manager.py:353] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:57 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.052 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:57 worker_manager.py:353] Main thread loading delta 6 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:57 worker_manager.py:353] Main thread loading delta 6 done
INFO 05-09 03:41:57 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
WARNING 05-09 03:41:57 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
INFO 05-09 03:41:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:41:57 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:57 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
[36m(RayWorkerVllm pid=86525)[0m WARNING 05-09 03:41:57 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:41:57 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:57 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
[36m(RayWorkerVllm pid=86687)[0m WARNING 05-09 03:41:57 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:57 models.py:268] [main] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:57 worker_manager.py:325] Adding delta 8 to prefetching queue: [8]
[36m(RayWorkerVllm pid=86917)[0m WARNING 05-09 03:41:57 worker_manager.py:335] Missed prefetch, fall back to loading delta 8 now
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:57 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:41:57 models.py:268] [main] Lossless Compression Disabled
INFO 05-09 03:41:59 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.558 seconds
INFO 05-09 03:41:59 worker_manager.py:353] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:00 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.052 seconds
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:00 worker_manager.py:353] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:41:59 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.032 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:00 worker_manager.py:353] Main thread loading delta 8 done
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:00 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.054 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:00 worker_manager.py:353] Main thread loading delta 8 done
INFO 05-09 03:42:00 worker_manager.py:325] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:00 worker_manager.py:325] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:00 worker_manager.py:325] Adding delta 4 to prefetching queue: [4]
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:00 worker_manager.py:325] Adding delta 4 to prefetching queue: [4]
INFO 05-09 03:42:00 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:42:00 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:01 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:01 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:01 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:01 models.py:268] [prefetching] Lossless Compression Disabled
INFO 05-09 03:42:02 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.598 seconds
INFO 05-09 03:42:02 worker_manager.py:278] Prefetching delta 4 done
INFO 05-09 03:42:02 metrics.py:276] Avg prompt throughput: 7.7 tokens/s, Avg generation throughput: 1.1 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 2 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:03 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.602 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:04 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.694 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:03 worker_manager.py:278] Prefetching delta 4 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:04 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.647 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:04 worker_manager.py:278] Prefetching delta 4 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:04 worker_manager.py:278] Prefetching delta 4 done
INFO 05-09 03:42:07 metrics.py:276] Avg prompt throughput: 4.3 tokens/s, Avg generation throughput: 6.3 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:42:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:42:16 worker_manager.py:325] Adding delta 7 to prefetching queue: [7]
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:16 worker_manager.py:325] Adding delta 7 to prefetching queue: [7]
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:16 worker_manager.py:325] Adding delta 7 to prefetching queue: [7]
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:16 worker_manager.py:325] Adding delta 7 to prefetching queue: [7]
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:17 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:17 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:17 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:17 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:17 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:17 models.py:268] [prefetching] Lossless Compression Disabled
INFO 05-09 03:42:17 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:42:17 models.py:268] [prefetching] Lossless Compression Disabled
INFO 05-09 03:42:17 worker_manager.py:325] Adding delta 3 to prefetching queue: [7, 3]
INFO 05-09 03:42:18 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.4 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 6 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:18 worker_manager.py:325] Adding delta 3 to prefetching queue: [7, 3]
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:18 worker_manager.py:325] Adding delta 3 to prefetching queue: [7, 3]
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:18 worker_manager.py:325] Adding delta 3 to prefetching queue: [7, 3]
INFO 05-09 03:42:18 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.483 seconds
INFO 05-09 03:42:18 worker_manager.py:278] Prefetching delta 7 done
INFO 05-09 03:42:19 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:42:19 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:19 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.937 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:20 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:20 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.965 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:20 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:20 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 3.063 seconds
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:20 worker_manager.py:278] Prefetching delta 7 done
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:21 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:21 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:21 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:21 models.py:268] [prefetching] Lossless Compression Disabled
INFO 05-09 03:42:21 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.488 seconds
INFO 05-09 03:42:21 worker_manager.py:278] Prefetching delta 3 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:21 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:21 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:23 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.337 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:23 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.320 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:23 worker_manager.py:278] Prefetching delta 3 done
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:23 worker_manager.py:278] Prefetching delta 3 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:23 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.249 seconds
INFO 05-09 03:42:23 metrics.py:276] Avg prompt throughput: 3.5 tokens/s, Avg generation throughput: 5.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 8 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:23 worker_manager.py:278] Prefetching delta 3 done
INFO 05-09 03:42:24 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:24 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:24 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:24 worker_manager.py:325] Adding delta 2 to prefetching queue: [2]
INFO 05-09 03:42:24 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:42:24 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:24 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:24 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:24 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:24 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:24 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:24 models.py:268] [prefetching] Lossless Compression Disabled
INFO 05-09 03:42:26 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.467 seconds
INFO 05-09 03:42:26 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:27 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.928 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:27 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.911 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:27 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:27 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.857 seconds
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:27 worker_manager.py:278] Prefetching delta 2 done
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:27 worker_manager.py:278] Prefetching delta 2 done
INFO 05-09 03:42:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 9 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:42:29 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:29 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:29 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:29 worker_manager.py:325] Adding delta 5 to prefetching queue: [5]
INFO 05-09 03:42:30 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.0.safetensors']
INFO 05-09 03:42:30 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:30 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.3.safetensors']
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:30 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:30 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.2.safetensors']
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:30 models.py:268] [prefetching] Lossless Compression Disabled
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:30 models.py:214] Loading from ['bitblas.remain.safetensors', 'bitblas.rank.1.safetensors']
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:30 models.py:268] [prefetching] Lossless Compression Disabled
INFO 05-09 03:42:31 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 1.486 seconds
INFO 05-09 03:42:31 worker_manager.py:278] Prefetching delta 5 done
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:33 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.614 seconds
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:33 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.731 seconds
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:33 models.py:324] Disk -> CPU: Loaded 1674.62 MiB in 2.603 seconds
[36m(RayWorkerVllm pid=86525)[0m INFO 05-09 03:42:33 worker_manager.py:278] Prefetching delta 5 done
[36m(RayWorkerVllm pid=86687)[0m INFO 05-09 03:42:33 worker_manager.py:278] Prefetching delta 5 done
[36m(RayWorkerVllm pid=86917)[0m INFO 05-09 03:42:33 worker_manager.py:278] Prefetching delta 5 done
INFO 05-09 03:42:34 metrics.py:276] Avg prompt throughput: 3.8 tokens/s, Avg generation throughput: 9.5 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 13 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:46398 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:42:39 metrics.py:276] Avg prompt throughput: 9.9 tokens/s, Avg generation throughput: 12.3 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 13 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:42:45 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 14 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:42:50 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.8 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 15 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
total threads: 23
INFO 05-09 03:42:55 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 17 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:43:00 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 17 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46380 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 17 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46441 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:46464 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:10 metrics.py:276] Avg prompt throughput: 39.0 tokens/s, Avg generation throughput: 15.5 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 10 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46368 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:46498 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:15 metrics.py:276] Avg prompt throughput: 11.2 tokens/s, Avg generation throughput: 20.1 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:43:21 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 24.1 tokens/s, Running: 10 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46550 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:26 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.4 tokens/s, Running: 9 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46532 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:31 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 20.5 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46390 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.8 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:43:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.9 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:43:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 17.9 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO:     ::1:46502 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:52 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.8 tokens/s, Running: 6 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO:     ::1:46402 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:43:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.9 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:02 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.9 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.7 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:12 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:17 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.0 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:22 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.8 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:27 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.8 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:32 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.9 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO:     ::1:46382 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:44:37 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.5 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:42 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.4 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:47 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.3 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 05-09 03:44:53 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 10.2 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO:     ::1:46412 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:44:58 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 8.6 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:03 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.8 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO:     ::1:46488 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:45:08 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.5 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:13 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO:     ::1:46387 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:45:18 metrics.py:276] Avg prompt throughput: 10.9 tokens/s, Avg generation throughput: 5.6 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46434 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:45:23 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 9.8 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:29 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.8 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO:     ::1:46466 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:45:34 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:39 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.1 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:44 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.1 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:49 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.1 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:54 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.1 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:45:59 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:46:05 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
INFO 05-09 03:46:10 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:46:15 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-09 03:46:20 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.1 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 4 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO:     ::1:46474 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:46:25 metrics.py:276] Avg prompt throughput: 8.5 tokens/s, Avg generation throughput: 5.5 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 2 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:46442 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:46544 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:46:31 metrics.py:276] Avg prompt throughput: 13.8 tokens/s, Avg generation throughput: 5.0 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:46:36 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-09 03:46:41 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 5.2 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:46428 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     ::1:46473 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:46:46 metrics.py:276] Avg prompt throughput: 4.0 tokens/s, Avg generation throughput: 3.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:46:51 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 4.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO:     ::1:46452 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 05-09 03:46:57 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 05-09 03:47:07 metrics.py:276] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
slurmstepd: error: *** JOB 3668365 ON HOST-10-140-60-2 CANCELLED AT 2024-05-09T03:47:10 ***
INFO:     Shutting down
